services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis  # Ensure Redis is started before the app

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    command: ["redis-server"]